/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "parsed_archc_isa.H"
#include  "parsed_archc_isa_isa.cpp"

#include  "parsed_archc_isa_syscall.H"

void* parsed_archc_isa::dispatch() {
  //!Updating Regs for behavioral simulation.
  if (ac_qk.need_sync()) {
    ac_qk.sync();
  }
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_VV.funct6 = ins_cache[1];
        instr_dec->F_Type_VV.vm = ins_cache[2];
        instr_dec->F_Type_VV.vs2 = ins_cache[3];
        instr_dec->F_Type_VV.vs1 = ins_cache[4];
        instr_dec->F_Type_VV.funct3 = ins_cache[5];
        instr_dec->F_Type_VV.vd = ins_cache[6];
        instr_dec->F_Type_VV.opcode = ins_cache[7];
      break;
      case 2:
        instr_dec->F_Type_VX.funct6 = ins_cache[1];
        instr_dec->F_Type_VX.vm = ins_cache[2];
        instr_dec->F_Type_VX.vs2 = ins_cache[3];
        instr_dec->F_Type_VX.rs1 = ins_cache[4];
        instr_dec->F_Type_VX.funct3 = ins_cache[5];
        instr_dec->F_Type_VX.vd = ins_cache[6];
        instr_dec->F_Type_VX.opcode = ins_cache[7];
      break;
      case 3:
        instr_dec->F_Type_VI.funct6 = ins_cache[1];
        instr_dec->F_Type_VI.vm = ins_cache[2];
        instr_dec->F_Type_VI.vs2 = ins_cache[3];
        instr_dec->F_Type_VI.imm = ins_cache[4];
        instr_dec->F_Type_VI.funct3 = ins_cache[5];
        instr_dec->F_Type_VI.vd = ins_cache[6];
        instr_dec->F_Type_VI.opcode = ins_cache[7];
      break;
      case 4:
        instr_dec->F_Type_MVV.funct6 = ins_cache[1];
        instr_dec->F_Type_MVV.vm = ins_cache[2];
        instr_dec->F_Type_MVV.vs2 = ins_cache[3];
        instr_dec->F_Type_MVV.vs1 = ins_cache[4];
        instr_dec->F_Type_MVV.funct3 = ins_cache[5];
        instr_dec->F_Type_MVV.vd = ins_cache[6];
        instr_dec->F_Type_MVV.opcode = ins_cache[7];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  ISA.cur_instr_id = ins_id;
  return instr_dec->end_rot;
}

void parsed_archc_isa::behavior() {

  void* vet[] = {&&I_Init, &&I_vand_vv_0, &&I_vmax_vx_1, &&I_vdiv_vx_2, &&I_vxor_vx_3, 
              &&I_vdiv_vx_4, &&I_vmax_vv_5, &&I_vdiv_vx_6, &&I_vor_vx_7, &&I_vsrl_vx_8, 
              &&I_vclz_m_9, &&I_vmin_vx_10, &&I_vmul_vv_11, &&I_vsrl_vv_12, &&I_vsadd_vx_13, 
              &&I_vmul_vv_14, &&I_vmax_vx_15};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_vand_vv_0: // Instruction vand_vv_0
    ISA._behavior_instruction(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ISA._behavior_parsed_archc_isa_Type_VV(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.vs1, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ISA.behavior_vand_vv_0(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.vs1, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vmax_vx_1: // Instruction vmax_vx_1
    ISA._behavior_instruction(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA._behavior_parsed_archc_isa_Type_VX(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA.behavior_vmax_vx_1(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vdiv_vx_2: // Instruction vdiv_vx_2
    ISA._behavior_instruction(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA._behavior_parsed_archc_isa_Type_VX(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA.behavior_vdiv_vx_2(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vxor_vx_3: // Instruction vxor_vx_3
    ISA._behavior_instruction(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA._behavior_parsed_archc_isa_Type_VX(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA.behavior_vxor_vx_3(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vdiv_vx_4: // Instruction vdiv_vx_4
    ISA._behavior_instruction(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA._behavior_parsed_archc_isa_Type_VX(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA.behavior_vdiv_vx_4(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vmax_vv_5: // Instruction vmax_vv_5
    ISA._behavior_instruction(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ISA._behavior_parsed_archc_isa_Type_VV(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.vs1, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ISA.behavior_vmax_vv_5(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.vs1, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vdiv_vx_6: // Instruction vdiv_vx_6
    ISA._behavior_instruction(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA._behavior_parsed_archc_isa_Type_VX(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA.behavior_vdiv_vx_6(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vor_vx_7: // Instruction vor_vx_7
    ISA._behavior_instruction(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA._behavior_parsed_archc_isa_Type_VX(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA.behavior_vor_vx_7(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vsrl_vx_8: // Instruction vsrl_vx_8
    ISA._behavior_instruction(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA._behavior_parsed_archc_isa_Type_VX(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA.behavior_vsrl_vx_8(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vclz_m_9: // Instruction vclz_m_9
    ISA._behavior_instruction(instr_dec->F_Type_MVV.funct6, instr_dec->F_Type_MVV.vm, instr_dec->F_Type_MVV.vs2, instr_dec->F_Type_MVV.funct3, instr_dec->F_Type_MVV.vd, instr_dec->F_Type_MVV.opcode);
    ISA._behavior_parsed_archc_isa_Type_MVV(instr_dec->F_Type_MVV.funct6, instr_dec->F_Type_MVV.vm, instr_dec->F_Type_MVV.vs2, instr_dec->F_Type_MVV.vs1, instr_dec->F_Type_MVV.funct3, instr_dec->F_Type_MVV.vd, instr_dec->F_Type_MVV.opcode);
    ISA.behavior_vclz_m_9(instr_dec->F_Type_MVV.funct6, instr_dec->F_Type_MVV.vm, instr_dec->F_Type_MVV.vs2, instr_dec->F_Type_MVV.vs1, instr_dec->F_Type_MVV.funct3, instr_dec->F_Type_MVV.vd, instr_dec->F_Type_MVV.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vmin_vx_10: // Instruction vmin_vx_10
    ISA._behavior_instruction(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA._behavior_parsed_archc_isa_Type_VX(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA.behavior_vmin_vx_10(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vmul_vv_11: // Instruction vmul_vv_11
    ISA._behavior_instruction(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ISA._behavior_parsed_archc_isa_Type_VV(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.vs1, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ISA.behavior_vmul_vv_11(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.vs1, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vsrl_vv_12: // Instruction vsrl_vv_12
    ISA._behavior_instruction(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ISA._behavior_parsed_archc_isa_Type_VV(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.vs1, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ISA.behavior_vsrl_vv_12(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.vs1, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vsadd_vx_13: // Instruction vsadd_vx_13
    ISA._behavior_instruction(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA._behavior_parsed_archc_isa_Type_VX(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA.behavior_vsadd_vx_13(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vmul_vv_14: // Instruction vmul_vv_14
    ISA._behavior_instruction(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ISA._behavior_parsed_archc_isa_Type_VV(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.vs1, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ISA.behavior_vmul_vv_14(instr_dec->F_Type_VV.funct6, instr_dec->F_Type_VV.vm, instr_dec->F_Type_VV.vs2, instr_dec->F_Type_VV.vs1, instr_dec->F_Type_VV.funct3, instr_dec->F_Type_VV.vd, instr_dec->F_Type_VV.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_vmax_vx_15: // Instruction vmax_vx_15
    ISA._behavior_instruction(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA._behavior_parsed_archc_isa_Type_VX(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ISA.behavior_vmax_vx_15(instr_dec->F_Type_VX.funct6, instr_dec->F_Type_VX.vm, instr_dec->F_Type_VX.vs2, instr_dec->F_Type_VX.rs1, instr_dec->F_Type_VX.funct3, instr_dec->F_Type_VX.vd, instr_dec->F_Type_VX.opcode);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void parsed_archc_isa::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void parsed_archc_isa::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void parsed_archc_isa::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void parsed_archc_isa::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void parsed_archc_isa::load(char* program) {
  DM_mport.load(program);
}

void parsed_archc_isa::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned parsed_archc_isa::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void parsed_archc_isa::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void parsed_archc_isa::PrintStat() {
  ac_arch<parsed_archc_isa_parms::ac_word, parsed_archc_isa_parms::ac_Hword>::PrintStat();
}

// Assigns value to processor frequency and updates cycle time values
void parsed_archc_isa::set_proc_freq(unsigned int proc_freq) {
  ac_module::set_proc_freq(proc_freq);
  time_1cycle=sc_time(1*module_period_ns, SC_NS);
}

