/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "parsed_archc_isa_arch.H"
#include  "parsed_archc_isa_arch_ref.H"

//!/Default constructor.
parsed_archc_isa_arch_ref::parsed_archc_isa_arch_ref(parsed_archc_isa_arch& arch) : ac_arch_ref<parsed_archc_isa_parms::ac_word, parsed_archc_isa_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc), ac_id(arch.ac_id),
  DM(arch.DM_mport),   VRB(arch.VRB),   XRB(arch.XRB) {}

