/******************************************************
 * AC_ISA Initialization File                         *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "parsed_archc_isa_isa.H"

//!Fields table declaration.
ac_dec_field parsed_archc_isa_parms::parsed_archc_isa_isa::fields[parsed_archc_isa_parms::AC_DEC_FIELD_NUMBER] = {
  {"funct6", 6, 31, 1, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[1])},
  {"vm", 1, 25, 2, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[2])},
  {"vs2", 5, 24, 3, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[3])},
  {"vs1", 5, 19, 4, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[4])},
  {"funct3", 3, 14, 5, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[5])},
  {"vd", 5, 11, 6, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[6])},
  {"opcode", 7, 6, 7, 0, 0, NULL},
  {"funct6", 6, 31, 1, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[8])},
  {"vm", 1, 25, 2, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[9])},
  {"vs2", 5, 24, 3, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[10])},
  {"rs1", 5, 19, 4, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[11])},
  {"funct3", 3, 14, 5, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[12])},
  {"vd", 5, 11, 6, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[13])},
  {"opcode", 7, 6, 7, 0, 0, NULL},
  {"funct6", 6, 31, 1, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[15])},
  {"vm", 1, 25, 2, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[16])},
  {"vs2", 5, 24, 3, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[17])},
  {"imm", 5, 19, 4, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[18])},
  {"funct3", 3, 14, 5, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[19])},
  {"vd", 5, 11, 6, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[20])},
  {"opcode", 7, 6, 7, 0, 0, NULL},
  {"funct6", 6, 31, 1, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[22])},
  {"vm", 1, 25, 2, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[23])},
  {"vs2", 5, 24, 3, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[24])},
  {"vs1", 5, 19, 4, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[25])},
  {"funct3", 3, 14, 5, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[26])},
  {"vd", 5, 11, 6, 0, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[27])},
  {"opcode", 7, 6, 7, 0, 0, NULL}
};

ac_dec_format parsed_archc_isa_parms::parsed_archc_isa_isa::formats[parsed_archc_isa_parms::AC_DEC_FORMAT_NUMBER] = {
  {1, "Type_VV", 32, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[0]), &(parsed_archc_isa_parms::parsed_archc_isa_isa::formats[1])},
  {2, "Type_VX", 32, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[7]), &(parsed_archc_isa_parms::parsed_archc_isa_isa::formats[2])},
  {3, "Type_VI", 32, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[14]), &(parsed_archc_isa_parms::parsed_archc_isa_isa::formats[3])},
  {4, "Type_MVV", 32, &(parsed_archc_isa_parms::parsed_archc_isa_isa::fields[21]), NULL}
};

ac_dec_list parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[parsed_archc_isa_parms::AC_DEC_LIST_NUMBER] = {
  {"funct6", 1, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[1])},
  {"funct3", 5, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[2])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[4])},
  {"funct3", 5, 4, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[5])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 2, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[7])},
  {"funct3", 5, 4, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[8])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 3, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[10])},
  {"funct3", 5, 4, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[11])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 4, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[13])},
  {"funct3", 5, 4, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[14])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 5, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[16])},
  {"funct3", 5, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[17])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 6, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[19])},
  {"funct3", 5, 4, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[20])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 7, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[22])},
  {"funct3", 5, 4, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[23])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 8, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[25])},
  {"funct3", 5, 4, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[26])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 9, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[28])},
  {"funct3", 5, 2, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[29])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 10, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[31])},
  {"funct3", 5, 4, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[32])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 11, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[34])},
  {"funct3", 5, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[35])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 12, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[37])},
  {"funct3", 5, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[38])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 13, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[40])},
  {"funct3", 5, 4, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[41])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 14, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[43])},
  {"funct3", 5, 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[44])},
  {"opcode", 7, 87, NULL},
  {"funct6", 1, 15, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[46])},
  {"funct3", 5, 4, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[47])},
  {"opcode", 7, 87, NULL}
};

ac_dec_instr parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[parsed_archc_isa_parms::AC_DEC_INSTR_NUMBER] = {
  {"vand_vv_0", 4, "vand_vv_0", "vand_vv_0 %vd, %vs2, %vs1", "Type_VV", 1, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[0]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[1])},
  {"vmax_vx_1", 4, "vmax_vx_1", "vmax_vx_1 %vd, %vs2, %rs1", "Type_VX", 2, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[3]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[2])},
  {"vdiv_vx_2", 4, "vdiv_vx_2", "vdiv_vx_2 %vd, %vs2, %rs1", "Type_VX", 3, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[6]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[3])},
  {"vxor_vx_3", 4, "vxor_vx_3", "vxor_vx_3 %vd, %vs2, %rs1", "Type_VX", 4, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[9]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[4])},
  {"vdiv_vx_4", 4, "vdiv_vx_4", "vdiv_vx_4 %vd, %vs2, %rs1", "Type_VX", 5, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[12]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[5])},
  {"vmax_vv_5", 4, "vmax_vv_5", "vmax_vv_5 %vd, %vs2, %vs1", "Type_VV", 6, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[15]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[6])},
  {"vdiv_vx_6", 4, "vdiv_vx_6", "vdiv_vx_6 %vd, %vs2, %rs1", "Type_VX", 7, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[18]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[7])},
  {"vor_vx_7", 4, "vor_vx_7", "vor_vx_7 %vd, %vs2, %rs1", "Type_VX", 8, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[21]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[8])},
  {"vsrl_vx_8", 4, "vsrl_vx_8", "vsrl_vx_8 %vd, %vs2, %rs1", "Type_VX", 9, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[24]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[9])},
  {"vclz_m_9", 4, "vclz_m_9", "vclz_m_9 %vd, %vs2, %vs1", "Type_MVV", 10, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[27]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[10])},
  {"vmin_vx_10", 4, "vmin_vx_10", "vmin_vx_10 %vd, %vs2, %rs1", "Type_VX", 11, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[30]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[11])},
  {"vmul_vv_11", 4, "vmul_vv_11", "vmul_vv_11 %vd, %vs2, %vs1", "Type_VV", 12, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[33]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[12])},
  {"vsrl_vv_12", 4, "vsrl_vv_12", "vsrl_vv_12 %vd, %vs2, %vs1", "Type_VV", 13, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[36]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[13])},
  {"vsadd_vx_13", 4, "vsadd_vx_13", "vsadd_vx_13 %vd, %vs2, %rs1", "Type_VX", 14, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[39]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[14])},
  {"vmul_vv_14", 4, "vmul_vv_14", "vmul_vv_14 %vd, %vs2, %vs1", "Type_VV", 15, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[42]), 0, &(parsed_archc_isa_parms::parsed_archc_isa_isa::instructions[15])},
  {"vmax_vx_15", 4, "vmax_vx_15", "vmax_vx_15 %vd, %vs2, %rs1", "Type_VX", 16, 1, 1, 1, &(parsed_archc_isa_parms::parsed_archc_isa_isa::dec_list[45]), 0, NULL}
};

const ac_instr_info
parsed_archc_isa_parms::parsed_archc_isa_isa::instr_table[parsed_archc_isa_parms::AC_DEC_INSTR_NUMBER + 1] = {
  ac_instr_info(0, "_ac_invalid_", "_ac_invalid_", 4),
  ac_instr_info(1, "vand_vv_0", "vand_vv_0", 4),
  ac_instr_info(2, "vmax_vx_1", "vmax_vx_1", 4),
  ac_instr_info(3, "vdiv_vx_2", "vdiv_vx_2", 4),
  ac_instr_info(4, "vxor_vx_3", "vxor_vx_3", 4),
  ac_instr_info(5, "vdiv_vx_4", "vdiv_vx_4", 4),
  ac_instr_info(6, "vmax_vv_5", "vmax_vv_5", 4),
  ac_instr_info(7, "vdiv_vx_6", "vdiv_vx_6", 4),
  ac_instr_info(8, "vor_vx_7", "vor_vx_7", 4),
  ac_instr_info(9, "vsrl_vx_8", "vsrl_vx_8", 4),
  ac_instr_info(10, "vclz_m_9", "vclz_m_9", 4),
  ac_instr_info(11, "vmin_vx_10", "vmin_vx_10", 4),
  ac_instr_info(12, "vmul_vv_11", "vmul_vv_11", 4),
  ac_instr_info(13, "vsrl_vv_12", "vsrl_vv_12", 4),
  ac_instr_info(14, "vsadd_vx_13", "vsadd_vx_13", 4),
  ac_instr_info(15, "vmul_vv_14", "vmul_vv_14", 4),
  ac_instr_info(16, "vmax_vx_15", "vmax_vx_15", 4)
};

const unsigned parsed_archc_isa_parms::parsed_archc_isa_isa::instr_format_table[parsed_archc_isa_parms::AC_DEC_INSTR_NUMBER + 1] = {
  0,
  1,
  2,
  2,
  2,
  2,
  1,
  2,
  2,
  2,
  4,
  2,
  1,
  1,
  2,
  1,
  2
};
